version: 0.2

env:
  variables:
    BUCKET_NAME: "myapp-demo-api-sam-serverless"
    STACK_PREFIX: "myapp-demo-api-sam"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "$CODEBUILD_WEBHOOK_BASE_REF | $CODEBUILD_WEBHOOK_HEAD_REF | $CODEBUILD_WEBHOOK_TRIGGER | $CODEBUILD_SOURCE_VERSION"
      # Only $CODEBUILD_WEBHOOK_TRIGGER return an ugly "branch/develop" when codebuild see new push. For manual and local build, the var is sadly empty.
      - BRANCH=$(echo "$CODEBUILD_WEBHOOK_TRIGGER" | sed 's/branch\///g')
      - if  [ -z "$BRANCH" ]; then BRANCH=$ENV; fi  
      # ^^ Please set $ENV var for local or manual build as I can not retreive $BRANCH var.
      - echo $BRANCH
      - env
      - npm --version
      - pip3 install awscli --upgrade
      - pip3 install aws-sam-cli --upgrade
  post_build:
    commands:
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket ${BUCKET_NAME}
      - sam deploy --template-file packaged.yaml --stack-name ${STACK_PREFIX}-${BRANCH} --s3-bucket ${BUCKET_NAME} --capabilities CAPABILITY_IAM --region eu-west-1